server.port: 9001
springfox.documentation.swagger.v2.path: /api-docs
#spring.jpa.hibernate.ddl-auto=none



spring:
    datasource:
        name: tb_test
        username: admin
        password: admin
        url: jdbc:postgresql://localhost:5432/tb_test
        driver-class-name: org.postgresql.Driver
        data:
            jpa:
                database: POSTGRES
                database-platform: POSTGRES
            jta:
                enabled: true

logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %magenta([%t]) %m%n"